from __future__ import annotations

import json
from importlib import resources

from .models import Coordinate, Discovery, DiscoveryKind


def load_seed_discoveries() -> list[Discovery]:
    data_path = resources.files(__package__) / "data" / "plaques.json"
    records = json.loads(data_path.read_text(encoding="utf-8"))
    return [discovery_from_record(record) for record in records]


def load_seed_blossom_discoveries() -> list[Discovery]:
    data_path = resources.files(__package__) / "data" / "freddys_blossom_walk.json"
    records = json.loads(data_path.read_text(encoding="utf-8"))
    return [discovery_from_record(record) for record in records]


def load_seed_listed_buildings() -> list[Discovery]:
    data_path = resources.files(__package__) / "data" / "listed_buildings.json"
    records = json.loads(data_path.read_text(encoding="utf-8"))
    return [discovery_from_record(record) for record in records]


def discovery_from_record(record: dict) -> Discovery:
    """Read the neutral discovery schema and the two legacy seed formats.

    Keeping this adapter means packaged data remains reproducible while importers
    can move to the explicit kind/collection/provenance schema independently.
    """
    collection = record.get("collection", record.get("scheme", "openplaques"))
    if str(collection).startswith("freddys-blossom"):
        inferred_kind = "blossom"
    elif collection == "historic-england-listed-buildings":
        inferred_kind = "listed-building"
    else:
        inferred_kind = "plaque"
    kind = DiscoveryKind(record.get("kind", inferred_kind))
    source_name = record.get("source_name", "")
    if not source_name:
        if kind is DiscoveryKind.BLOSSOM:
            source_name = "Freddy's Blossom Walk"
        elif kind is DiscoveryKind.LISTED_BUILDING:
            source_name = "Historic England"
        else:
            source_name = "Open Plaques"
    attributes = dict(record.get("attributes", {}))
    if record.get("colour"):
        attributes.setdefault("colour", str(record["colour"]))
    return Discovery(
        id=str(record["id"]),
        title=record["title"],
        description=record.get("description", ""),
        coordinate=Coordinate(float(record["lat"]), float(record["lon"])),
        address=record.get("address", ""),
        kind=kind,
        collection=collection,
        source_name=source_name,
        source_url=record.get("source_url", ""),
        image_url=record.get("image_url", ""),
        external_id=str(record.get("external_id", record.get("openplaques_id", ""))),
        borough=record.get("borough", ""),
        is_accurate=bool(record.get("is_accurate", False)),
        curation_status=record.get("curation_status", "candidate"),
        curation_note=record.get("curation_note", ""),
        route_order=record.get("route_order"),
        attributes=attributes,
    )


def discoveries_from_openplaques_geojson(payload: dict, borough_name: str = "lewisham") -> list[Discovery]:
    """Import legacy/full Open Plaques GeoJSON that includes borough-like properties.

    The current bundled fixture is generated by scripts/import_openplaques.py because
    the Open Plaques London thin dump only includes id, inscription, and geometry.
    """
    discoveries: list[Discovery] = []
    for feature in payload.get("features", []):
        props = feature.get("properties", {})
        geometry = feature.get("geometry", {})
        coordinates = geometry.get("coordinates") or []
        if len(coordinates) < 2:
            continue
        text = " ".join(str(props.get(key, "")) for key in ("title", "inscription", "address", "organisation"))
        colour = str(props.get("colour") or props.get("colour_name") or "").lower()
        if borough_name.lower() not in text.lower() and "lewisham" not in str(props).lower():
            continue
        if colour and not any(candidate in colour for candidate in ("brown", "maroon")):
            continue
        discoveries.append(
            Discovery(
                id=str(props.get("id") or props.get("plaque_id") or len(discoveries) + 1),
                title=str(props.get("title") or props.get("person") or "Unnamed plaque"),
                description=str(props.get("inscription") or props.get("description") or ""),
                coordinate=Coordinate(float(coordinates[1]), float(coordinates[0])),
                address=str(props.get("address") or ""),
                kind=DiscoveryKind.PLAQUE,
                collection="openplaques",
                source_name="Open Plaques",
                source_url=str(props.get("uri") or props.get("url") or ""),
                image_url=str(props.get("main_photo") or props.get("image") or ""),
                borough=borough_name.title(),
                external_id=str(props.get("id") or props.get("plaque_id") or ""),
                attributes={"colour": colour or "brown"},
            )
        )
    return discoveries
